import type { Member, OtAssignmentWithDetails } from '@/types'

export const DEMO_MEMBERS: Member[] = [
  {
    id: 'member-001', name: '정유림', phone: '01093786577', gender: '여',
    sports: ['헬스'], duration_months: null, exercise_time: '저녁',
    injury_tags: [], notes: null, ot_category: '헬스',
    detail_info: '기월10,100/WPT3회씩/근력/체력/건강관리/주말쉼',
    start_date: '2025-03-24', is_completed: true, is_renewal: false,
    registered_at: '2025-03-21', created_by: null,
    created_at: '2025-03-21T09:00:00Z', updated_at: '2025-03-21T09:00:00Z',
  },
  {
    id: 'member-002', name: '이다원', phone: '01021144170', gender: '여',
    sports: [], duration_months: null, exercise_time: '모름',
    injury_tags: [], notes: null, ot_category: '거부',
    detail_info: '헬12/OT거부',
    start_date: null, is_completed: false, is_renewal: false,
    registered_at: '2025-03-21', created_by: null,
    created_at: '2025-03-21T10:00:00Z', updated_at: '2025-03-21T10:00:00Z',
  },
  {
    id: 'member-003', name: '김예윤', phone: '01079403678', gender: '여',
    sports: ['헬스'], duration_months: null, exercise_time: '18시이후',
    injury_tags: [], notes: null, ot_category: '헬스',
    detail_info: '기월10,100/WPT3회씩/건강/체력증진/부상부위X/18시이후/PT경험없음오래받음',
    start_date: '2025-03-24', is_completed: true, is_renewal: false,
    registered_at: '2025-03-21', created_by: null,
    created_at: '2025-03-21T11:00:00Z', updated_at: '2025-03-21T11:00:00Z',
  },
  {
    id: 'member-004', name: '박채원', phone: '01045188623', gender: '여',
    sports: ['PT등록'], duration_months: null, exercise_time: '평일20시이후',
    injury_tags: [], notes: null, ot_category: 'PT등록',
    detail_info: '기월5,50/WPT3회씩/자세교정/주말/평일20시이후/허리통증있는편/라운드숄더/헬스-기구사용법',
    start_date: '2025-03-24', is_completed: true, is_renewal: false,
    registered_at: '2025-03-21', created_by: null,
    created_at: '2025-03-21T12:00:00Z', updated_at: '2025-03-21T12:00:00Z',
  },
  {
    id: 'member-005', name: '이상민', phone: '01090435396', gender: '남',
    sports: ['PT등록'], duration_months: null, exercise_time: '오전 8:30',
    injury_tags: [], notes: null, ot_category: 'PT등록',
    detail_info: '헬12/WPT3회씩/취미/오전8시30분/원목무릎원쪽아래얀출술/헬스-석현블로핑',
    start_date: '2025-03-23', is_completed: true, is_renewal: false,
    registered_at: '2025-03-22', created_by: null,
    created_at: '2025-03-22T09:00:00Z', updated_at: '2025-03-22T09:00:00Z',
  },
  {
    id: 'member-006', name: '유황형', phone: '01094047248', gender: '남',
    sports: ['PT등록'], duration_months: null, exercise_time: '유동적',
    injury_tags: [], notes: null, ot_category: 'PT등록',
    detail_info: '기월3/WPT3회씩/유동적/어깨이터플릭스/디스크X메탈조건/그외부상통증없음/웨이트학생/PT-태우/PPT-해리플로핑',
    start_date: '2025-03-24', is_completed: true, is_renewal: false,
    registered_at: '2025-03-23', created_by: null,
    created_at: '2025-03-23T10:00:00Z', updated_at: '2025-03-23T10:00:00Z',
  },
  {
    id: 'member-007', name: '조은주', phone: '01073005376', gender: '여',
    sports: [], duration_months: null, exercise_time: '모름',
    injury_tags: [], notes: null, ot_category: '거부',
    detail_info: '헬12/WPT3회씩/추후결정',
    start_date: null, is_completed: false, is_renewal: false,
    registered_at: '2025-03-23', created_by: null,
    created_at: '2025-03-23T11:00:00Z', updated_at: '2025-03-23T11:00:00Z',
  },
  {
    id: 'member-008', name: '장수연', phone: '01041103468', gender: '여',
    sports: ['헬스'], duration_months: null, exercise_time: '19시이후',
    injury_tags: [], notes: null, ot_category: '헬스',
    detail_info: '기월6,48/WPT3회씩/근력/체력/건강/19시이후/주말운동적/필라테스외치료/헬트걸치처클/정경핸/PT-기구사용법',
    start_date: '2025-03-31', is_completed: true, is_renewal: false,
    registered_at: '2025-03-24', created_by: null,
    created_at: '2025-03-24T14:00:00Z', updated_at: '2025-03-24T14:00:00Z',
  },
]

const todayStr = new Date().toISOString().split('T')[0]

export const DEMO_OT_ASSIGNMENTS: OtAssignmentWithDetails[] = [
  {
    id: 'ot-001', member_id: 'member-001', status: '완료', ot_category: '헬스',
    pt_trainer_id: 'demo-trainer-001', ppt_trainer_id: null,
    assigned_by: 'demo-admin-001', notes: null,
    registration_type: null, registration_route: null, expected_sales: 0, actual_sales: 0, week_number: 1, membership_start_date: null, contact_status: '정상', sales_status: 'OT진행중', expected_amount: 0, closing_probability: 0, closing_fail_reason: null, sales_note: null, is_sales_target: false, is_pt_conversion: false, pt_assign_status: 'none', ppt_assign_status: 'none', is_excluded: false, excluded_reason: null, excluded_at: null,
    created_at: '2025-03-21T09:00:00Z', updated_at: '2025-03-24T09:00:00Z',
    member: DEMO_MEMBERS[0],
    pt_trainer: { id: 'demo-trainer-001', name: '박트레이너' },
    ppt_trainer: null,
    sessions: [
      { id: 's1', ot_assignment_id: 'ot-001', session_number: 1, scheduled_at: '2025-03-24T18:00:00Z', completed_at: '2025-03-24T19:00:00Z', feedback: '기초 체력 양호', exercise_content: null, trainer_tip: null, cardio_type: null, cardio_duration: null, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'ot-002', member_id: 'member-002', status: '거부', ot_category: '거부',
    pt_trainer_id: null, ppt_trainer_id: null,
    assigned_by: null, notes: 'OT 거부',
    registration_type: null, registration_route: null, expected_sales: 0, actual_sales: 0, week_number: 1, membership_start_date: null, contact_status: '정상', sales_status: 'OT진행중', expected_amount: 0, closing_probability: 0, closing_fail_reason: null, sales_note: null, is_sales_target: false, is_pt_conversion: false, pt_assign_status: 'none', ppt_assign_status: 'none', is_excluded: false, excluded_reason: null, excluded_at: null,
    created_at: '2025-03-21T10:00:00Z', updated_at: '2025-03-21T10:00:00Z',
    member: DEMO_MEMBERS[1],
    pt_trainer: null, ppt_trainer: null, sessions: [],
  },
  {
    id: 'ot-003', member_id: 'member-003', status: '배정완료', ot_category: '헬스',
    pt_trainer_id: 'demo-trainer-001', ppt_trainer_id: null,
    assigned_by: 'demo-admin-001', notes: null,
    registration_type: null, registration_route: null, expected_sales: 0, actual_sales: 0, week_number: 1, membership_start_date: null, contact_status: '정상', sales_status: 'OT진행중', expected_amount: 0, closing_probability: 0, closing_fail_reason: null, sales_note: null, is_sales_target: false, is_pt_conversion: false, pt_assign_status: 'none', ppt_assign_status: 'none', is_excluded: false, excluded_reason: null, excluded_at: null,
    created_at: '2025-03-21T11:00:00Z', updated_at: '2025-03-22T10:00:00Z',
    member: DEMO_MEMBERS[2],
    pt_trainer: { id: 'demo-trainer-001', name: '박트레이너' },
    ppt_trainer: null,
    sessions: [
      { id: 's2', ot_assignment_id: 'ot-003', session_number: 1, scheduled_at: `${todayStr}T18:00:00Z`, completed_at: null, feedback: null, exercise_content: null, trainer_tip: null, cardio_type: null, cardio_duration: null, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'ot-004', member_id: 'member-004', status: '진행중', ot_category: 'PT등록',
    pt_trainer_id: 'demo-trainer-001', ppt_trainer_id: null,
    assigned_by: 'demo-admin-001', notes: null,
    registration_type: null, registration_route: null, expected_sales: 0, actual_sales: 0, week_number: 1, membership_start_date: null, contact_status: '정상', sales_status: 'OT진행중', expected_amount: 0, closing_probability: 0, closing_fail_reason: null, sales_note: null, is_sales_target: false, is_pt_conversion: false, pt_assign_status: 'none', ppt_assign_status: 'none', is_excluded: false, excluded_reason: null, excluded_at: null,
    created_at: '2025-03-21T12:00:00Z', updated_at: '2025-03-22T11:00:00Z',
    member: DEMO_MEMBERS[3],
    pt_trainer: { id: 'demo-trainer-001', name: '박트레이너' },
    ppt_trainer: null,
    sessions: [
      { id: 's3', ot_assignment_id: 'ot-004', session_number: 1, scheduled_at: '2025-03-24T20:00:00Z', completed_at: '2025-03-24T21:00:00Z', feedback: '자세교정 위주 진행', exercise_content: null, trainer_tip: null, cardio_type: null, cardio_duration: null, created_at: '', updated_at: '' },
      { id: 's4', ot_assignment_id: 'ot-004', session_number: 2, scheduled_at: `${todayStr}T20:00:00Z`, completed_at: null, feedback: null, exercise_content: null, trainer_tip: null, cardio_type: null, cardio_duration: null, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'ot-005', member_id: 'member-005', status: '신청대기', ot_category: 'PT등록',
    pt_trainer_id: null, ppt_trainer_id: null,
    assigned_by: null, notes: null,
    registration_type: null, registration_route: null, expected_sales: 0, actual_sales: 0, week_number: 1, membership_start_date: null, contact_status: '정상', sales_status: 'OT진행중', expected_amount: 0, closing_probability: 0, closing_fail_reason: null, sales_note: null, is_sales_target: false, is_pt_conversion: false, pt_assign_status: 'none', ppt_assign_status: 'none', is_excluded: false, excluded_reason: null, excluded_at: null,
    created_at: '2025-03-22T09:00:00Z', updated_at: '2025-03-22T09:00:00Z',
    member: DEMO_MEMBERS[4],
    pt_trainer: null, ppt_trainer: null, sessions: [],
  },
  {
    id: 'ot-006', member_id: 'member-006', status: '신청대기', ot_category: 'PT등록',
    pt_trainer_id: null, ppt_trainer_id: null,
    assigned_by: null, notes: null,
    registration_type: null, registration_route: null, expected_sales: 0, actual_sales: 0, week_number: 1, membership_start_date: null, contact_status: '정상', sales_status: 'OT진행중', expected_amount: 0, closing_probability: 0, closing_fail_reason: null, sales_note: null, is_sales_target: false, is_pt_conversion: false, pt_assign_status: 'none', ppt_assign_status: 'none', is_excluded: false, excluded_reason: null, excluded_at: null,
    created_at: '2025-03-23T10:00:00Z', updated_at: '2025-03-23T10:00:00Z',
    member: DEMO_MEMBERS[5],
    pt_trainer: null, ppt_trainer: null, sessions: [],
  },
  {
    id: 'ot-007', member_id: 'member-007', status: '거부', ot_category: '거부',
    pt_trainer_id: null, ppt_trainer_id: null,
    assigned_by: null, notes: '추후결정',
    registration_type: null, registration_route: null, expected_sales: 0, actual_sales: 0, week_number: 3, membership_start_date: null, contact_status: '정상', sales_status: 'OT진행중', expected_amount: 0, closing_probability: 0, closing_fail_reason: null, sales_note: null, is_sales_target: false, is_pt_conversion: false, pt_assign_status: 'none', ppt_assign_status: 'none', is_excluded: false, excluded_reason: null, excluded_at: null,
    created_at: '2025-03-23T11:00:00Z', updated_at: '2025-03-23T11:00:00Z',
    member: DEMO_MEMBERS[6],
    pt_trainer: null, ppt_trainer: null, sessions: [],
  },
  {
    id: 'ot-008', member_id: 'member-008', status: '배정완료', ot_category: '헬스',
    pt_trainer_id: 'demo-trainer-001', ppt_trainer_id: null,
    assigned_by: 'demo-admin-001', notes: null,
    registration_type: null, registration_route: null, expected_sales: 0, actual_sales: 0, week_number: 1, membership_start_date: null, contact_status: '정상', sales_status: 'OT진행중', expected_amount: 0, closing_probability: 0, closing_fail_reason: null, sales_note: null, is_sales_target: false, is_pt_conversion: false, pt_assign_status: 'none', ppt_assign_status: 'none', is_excluded: false, excluded_reason: null, excluded_at: null,
    created_at: '2025-03-24T14:00:00Z', updated_at: '2025-03-25T09:00:00Z',
    member: DEMO_MEMBERS[7],
    pt_trainer: { id: 'demo-trainer-001', name: '박트레이너' },
    ppt_trainer: null, sessions: [],
  },
]
